name: "Set up Docker"
description: "Set up Docker on Linux, macOS, or Windows. On macOS and Windows, use Podman for running containers."
runs:
  using: composite
  steps:
    - name: Install Podman
      if: runner.os == 'Windows'
      shell: bash
      run: |
        wsl --update --web-download
        net stop docker || true
        choco install podman-cli
        podman machine init
        podman machine start
    - name: Install Podman
      if: runner.os == 'macOS' && runner.arch == 'X64'
      shell: bash
      run: |
        curl -OL https://github.com/podman-container-tools/podman/releases/download/v5.8.8/podman-installer-macos-amd64.pkg
        sudo installer -verbose -pkg podman-installer-macos-amd64.pkg -target /
        brew update
        brew install --build-from-source docker
        sudo /opt/podman/bin/podman-mac-helper install
        /opt/podman/bin/podman machine init
        /opt/podman/bin/podman machine start
    - name: Install Podman
      if: runner.os == 'macOS' && runner.arch == 'ARM64'
      shell: bash
      run: |
        brew install docker podman
        sudo podman-mac-helper install
        podman machine init
        podman machine start
